spring:
  datasource:
    master:
      driver-class-nam: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cloudDB01?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT&allowMultiQueries=true&allowPublicKeyRetrieval=true
      username: root
      password: ROOT1234
    slave:
      driver-class-nam: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cloudDB02?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT&allowMultiQueries=true&allowPublicKeyRetrieval=true
      username: root
      password: ROOT1234

  devtools:
    restart:
      #设置重启的目录
      additional-paths: src/main/java
      #classpath目录下的WEB-INF文件夹内容修改不重启
      exclude: WEB-INF/**
  flyway:
    out-of-order: true
    baseline-on-migrate: true